[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "GPL-3.0-only",
    "Zlib",
    "BSL-1.0",
    "Unicode-3.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unlicense",
    "LGPL-2.1-or-later",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "NCSA",
]

[advisories]
ignore = [
    "RUSTSEC-2024-0436",
]
